### ISSUE TITLE
XLSX Import - ignore empty values so a not necessary objectbrick will be created

### ISSUE THREAD

**Issue by shaselboeck** [pimcore/data-importer#152]
I have a data object class "TravelPosition" with the following attributes (shortened section):
- name (Type: Input)
- travelType (Type: Objectbricks) 
![](https://drive.google.com/uc?export=view&id=109vVv-uQxhnCv_tSTx36dwB1A18zmN2q)

Allowed objectbricks can be:
- TravelPositionBus
   - busMeetingPoint
   - busFrom
   - busTo
   - etc.
![](https://drive.google.com/uc?export=view&id=1Fb0pm45JCR8tghPv_TgwRZR8eV7jtUqv)
- TravelPositionFlight
   - flightAirline
   - flightBookingCode
   - flightTerminal
   - flightNumber
   - etc.
![](https://drive.google.com/uc?export=view&id=1ByXYYHe8PHTn27cVNhyb9RCHNSQIFUrf)
- TravelPositionHotel
- TravelPositionTrain

I import the travel positions via a XLSX file, where all possible data are in one line:
- name
- flightAirline
- flightBookingCode
- flightTerminal
- flightNumber
- busMeetingPoint
- busFrom
- busTo
- trainStation
- trainFrom
- trainTo
- hotelWebsite
- hotelPhone
- and a few more
![](https://drive.google.com/uc?export=view&id=1WyeeX84hqH4qIUjm_uyu_wXSin63iZRL)

A travel position can have a maximum of one object brick, i.e. either bus, flight, hotel or train. But this does not work because all Objectbricks are always created, even if all fields for bus, hotel and train are empty and only those for one flight are filled.
![](https://drive.google.com/uc?export=view&id=1gQ2LgP7b5LeG92Yv-rgJOwOnTZTTl9xk)

In order for it to work that way, I have set max. Items from 1 to 4 for "travelType" (type: objectbrick) in data object class "TravelPosition".

It would be great if there was a possibility that certain fields are simply ignored for a certain value (here empty string) so that the 3 unnecessary object bricks are not available with empty values. Is there a sensible solution for this or one that is in prospect?

**Comment by fashxp** [comment]
![image](https://user-images.githubusercontent.com/8792145/148966165-f5ba6258-d9ca-4c4c-8dc7-bf7fff14ffbf.png)

does deactivating this option solve that issue?

**Comment by shaselboeck** [comment]
I'm sorry, but unfortunately I can't test that. I no longer use the Data Importer. The project was time-sensitive, so I programmed my own import routine.

**Comment by fashxp** [comment]
closed due to inactivity. should be fixed.

**Comment by mdares** [comment]
I am confirming this is still an issue - even with the "If source is empty" check box unclicked, Pimcore will create a brick for any bricks there is a mapping for, especially troublesome when there are default values set on the brick.
