### ISSUE TITLE
[Bug]: DataObjectLoader::loadByAttribute requires $identifier not to be null

### ISSUE THREAD

**Issue by rjankiew** [pimcore/data-importer#182]
### Expected behavior

When using "find parent" location strategy for element creation or update, if parent identifier is not specified in row (is empty, null), fallback path should be used to load parent. 

### Actual behavior

An error occurs:
```
Failed to process "71064": Pimcore\Bundle\DataImporterBundle\Tool\DataObjectLoader::loadByAttribute(): Argument #3 ($identifier) must be of type string, null given, called in /var/www/pimcore/vendor/pimcore/data-importer/src/Resolver/Location/FindParentStrategy.php on line 121
```

and **processing is stuck on this row**.

### Steps to reproduce

Create configuration that uses "Find Parent" location strategy for "Element Location Update" and "Element Creation", set up "Attribute" find strategy. Try to import a row with empty data under configured "Data Source Index".

As far as I can see in source code, the same issue will occur with other find strategies.

**Comment by mcop1** [comment]
Resolved by #184

**Comment by rjankiew** [comment]
@mcop1 this issue is still present in 1.6.0, but for other strategies. It's ok for `FindParentStragegy`, but still I'm getting:
```
Failed to process "71360": Pimcore\Bundle\DataImporterBundle\Tool\DataObjectLoader::loadByAttribute(): Argument #3 ($identifier) must be of type string, null given, called in /var/www/pimcore/vendor/pimcore/data-importer/src/Resolver/Load/AttributeStrategy.php on line 70
```
when using e.g. `AttributeStrategy`.
