### ISSUE TITLE
[Bug]: Migration is failing

### ISSUE THREAD

**Issue by matthiashamacher** [pimcore/data-importer#199]
### Expected behavior

When installing or updating the data importer the migrations should be executed correctly and no errors should be thrown.

### Actual behavior

When executing the migrations the following error occurs:

> The column 'dispatched' on table 'bundle_data_hub_data_importer_queue' already exists.

### Steps to reproduce

This is because [Version20220304130000](https://github.com/pimcore/data-importer/blob/1.x/src/Migrations/Version20220304130000.php) tries to add columns that already exist if the bundle is installed for the first time. In the Queue Service, there is a function that creates that table with all the columns: https://github.com/pimcore/data-importer/blob/1.x/src/Queue/QueueService.php#L73

**Comment by fashxp** [comment]
hmm, question is, why this migration is executed after the fresh install?

**Comment by matthiashamacher** [comment]
It's not necessary a new install of the bundle but a new install of the whole pimcore setup. We are running a build test in our pipelines which installs pimcore from zero. As the bundle is in the composer.json and enabled through the bundles.php the Migrations are executed afterward.

I know, that the migrations of the pimcore core are marked as executed if pimcore is freshly installed, maybe something like that must be done for this bundle as well?

**Comment by fashxp** [comment]
But that should be the case when installing the bundle ... it marks all migrations as migrated prior to that one https://github.com/pimcore/data-importer/blob/1.x/src/Installer.php#L45

That's why I'm wondering. So maybe you need to install the bundles in your routine too?

**Comment by Chris-Gett** [comment]
@fashxp is that Problem aleady fixed with that issue #181 ? I think these two issues are more or less related to each other.

**Comment by matthiashamacher** [comment]
@fashxp Yes installing the bundles first, fixed the issue in this case.

But I know have a similar issue with the headless-documents bundle in the latest version where installing first does not fix the issue. I created an issue in that repository.

**Comment by rjankiew** [comment]
@matthiashamacher how to go about this when updating the bundle? Should I mark Version20220304130000 as migrated manually? By the way, for me its the same with Version20211201173215.

**Comment by matthiashamacher** [comment]
@rjankiew That was my temporary solution, yes. But it's not a nice one and should be used only temporarily. Normally that shouldn't happen during the update as the changes shouldn't exist previously. 

Regarding Version20211201173215, what is the exact error message? [The migration checks if the old table](https://github.com/pimcore/data-importer/blob/1.x/src/Migrations/Version20211201173215.php#L53) exists so there should definitely be no problem during update if the table is already renamed.

**Comment by rjankiew** [comment]
@matthiashamacher I see it checks if the old table exist, but I feel the problem is that the new table exists already, too. So maybe somehow the old table did not get deleted? I already marked it as executed, so I won't be able to reproduce easily.
