### ISSUE TITLE
[Preview] ImportAsset operator throws exception

### ISSUE THREAD

**Issue by fashxp** [pimcore/data-importer#46]
when loading preview in mapping UI

![image](https://user-images.githubusercontent.com/8792145/123755802-93cbf280-d8bc-11eb-9686-f6e6f6d38dbd.png)

Pimcore\Bundle\DataImporterBundle\Mapping\Operator\Simple\ImportAsset::process:80

**Comment by fashxp** [comment]
probably fixed with https://github.com/pimcore/data-importer/pull/48

**Comment by creativehubspace** [comment]
How does the import handle the asset when the url to fetch the asset returns a 404 response? I am still getting the exeption thrown.
![dataimport](https://user-images.githubusercontent.com/13438312/217488436-d5573377-90e3-4ea7-bd92-39068e408476.png)
