### ISSUE TITLE
[Improvement]: Direct Data Target extension "Overwrite selection"

### ISSUE THREAD

**Issue by js-aw** [pimcore/data-importer#97]
### Improvement description

I am on the 1.x-dev branch and updated to the latest version. I noticed that for new objects the system key is no longer set correctly and instead a unique id is set as key although a field was mapped in the import for the key. 
In the meantime I could find out that it is due to changes from #88. Via the pull request the feature "Overwrite selection" came in, with the options "If source is empty" and "If destination is not empty". 

I think this is more a feature than a bug, that now the two options have to be set explicitly for the system key and all other mapped fields...?!

Would be good to add this to the documentation because after the version update the key is not taken over during the import and the changes are not written for mapped fields.

**Comment by fashxp** [comment]
Thx for the hint. I think we should try to keep the same behavior. 
Setting `If source is empty` to true by default should restore the same behavior, doesn't it? 
@woellundwoell

**Comment by woellundwoell** [comment]
Yes, I think so. ;)
Should we change it in the PR?

**Comment by fashxp** [comment]
PR is already merged, would need to be a new one

**Comment by fashxp** [comment]
should be fixed with #100

**Comment by ghost** [comment]
@fashxp 

Hallo Christian,  unfortunately after #100 it seems that for new objects the system key is still not set correctly and instead a unique id is set as key although a field was mapped in the import for the key.

tested on:
    pimcore/data-hub: 1.0
    pimcore/data-importer: 1.3.0
    pimcore/pimcore: 10.1.5


I have mapped the product name as key but still a unique id is assigned to the data objects:

![grafik](https://user-images.githubusercontent.com/68632142/141477522-eb711108-3fb4-4d06-8280-76c07d5ee601.png)

![grafik](https://user-images.githubusercontent.com/68632142/141477615-49070580-6bf4-4a8a-9c52-736595f497ba.png)

![grafik](https://user-images.githubusercontent.com/68632142/141479067-e8e31ef9-d236-4180-a59c-979a56e6a263.png)

![grafik](https://user-images.githubusercontent.com/68632142/141479824-e50adb20-d234-4f8e-885b-46c52c58b88b.png)

And when I check both overwrite options an error is generated for all data objects

![grafik](https://user-images.githubusercontent.com/68632142/141480591-a53aa1b0-e632-4536-9036-2e216464f9bf.png)

![grafik](https://user-images.githubusercontent.com/68632142/141480773-e212cb65-4c55-4ccd-88dd-8d8ba2b8f161.png)

Thanks

**Comment by fashxp** [comment]
you need to definitely activate the checkboxes. If I do so, it works just fine for me. 
maybe your key contains any invalid characters?
